### PR TITLE
Mel dev

### PR DESCRIPTION
**Pull request by lifewithphish**
Short series of commits which add the ability to do a place details request. Once we have decided what we want to access (photos may be an option as well) it will be ready for bootstrapping

### CODE REVIEW

**Review by cliaer — APPROVED** [review]
Looks like everything works so far in terms of the marker. Need UI implementation to see what happens when no restaurant is returned/restaurant is null.

**Review by alicethu — APPROVED** [review]
@lifewithphish looks good to me too! if anything, I'd display more relevant info to the user when clicking on the place marker (atm it just displays the name of the restaurant, place id, and address). the place id isn't really relevant to users

**Comment by alicethu** [comment]
> Looks like everything works so far in terms of the marker. Need UI implementation to see what happens when no restaurant is returned/restaurant is null.

@cliaer I tested this by shrinking the radius to force empty results. The marker simply wouldn't appear, which seems like a reasonable response.

**Comment by alicethu** [comment]
@yinlow63 we need to display/format the information that Mel's request saves in the sidebar

**Pull request merged**
